name: global_solar_client_app
description: "Global Solar 2.0 — Client Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.3
  google_fonts: ^8.2.1
  url_launcher: ^6.3.2
  share_plus: ^13.3.0
  uuid: ^4.6.0
  pdf: ^3.10.16
  printing: ^5.13.0
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0
  webview_flutter: ^4.14.1
  html_to_pdf: ^0.8.1
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/templates/quotation.html
    - assets/templates/quotation_gu.html
    - assets/data/estimate_master.json
    - assets/images/logo.jpg
    - assets/images/logo.png
    - assets/images/hero_solar_installation.jpg
    - assets/images/hero_installation.jpg
    - assets/images/solar_installation_detail.jpg
    - assets/images/solar_structure_detail.jpg
    - assets/images/solar_rooftop_overview.jpg
    - assets/images/design_view_top.jpg
    - assets/images/design_view_left.jpg
    - assets/images/design_view_right.jpg
    - assets/images/solar_panel_detail.jpg
    - assets/images/solar_pannel_6.png
    - assets/images/solar_pannel_5.jpg
    - assets/images/solar_pannel_7.jpg
    - assets/images/solar_pannel_8.jpg
    - assets/images/solar_pannel_9.jpg
    - assets/images/solar_pannel_10.jpg
    - assets/fonts/sans_serif.ttf
